version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: attendance_management
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mounts init script

    ports:
      - "3306:3306"  # Exposes MySQL to host system

  admin:
    image: adminer
    restart: always
    depends_on:
      - db172.18.0.2
      - "8080:8080"

volumes:
  mysql_data:
